### ISSUE TITLE
reference syntax highlight

### ISSUE THREAD

**Issue by DOFfactory** [notZaki/PandocCiter#1]
It would be beneficial, if you would introduce a scope for the references (i.e. both for `@reference` and `[@reference]`) in order to be able to provide syntax highlight with the theme installed.

At the moment the references to citations are the same colour as the main text, making the finding of references very difficult.

**Comment by notZaki** [comment]
That's a great idea.

Scopes for both types of references, named `pandoc.citation.inline` and `pandoc.citation.block`, should be available in the new release. Here's an example image below:
![image](https://user-images.githubusercontent.com/9019681/46438700-88a80000-c72c-11e8-8c71-4d671ffa55c1.png)

By default, the references will not have any highlighting applied to them.
To enable highlighting for references, define a highlight colour by entering the following in vscode's settings JSON:
```
"editor.tokenColorCustomizations": {
        "[<<USER_THEME_NAME>>]": {
            "textMateRules": [
                {
                    "scope": "pandoc.citation",
                    "settings": {
                        "foreground": "<<HIGHLIGHT_COLOUR>>"
                    }
                }
            ]
        }
    }
```
but replace `<<USER_THEME_NAME>>`  with the theme being used, and `<<HIGHLIGHT_COLOUR>>` with the desired colour for the references. That should do the trick.

**Comment by DOFfactory** [comment]
@notZaki BIG THANK YOU for the quick response! I can confirm the update works as expected and demonstrated on the screenshot above. You saved a lot of my time this evening (and in the future), that's for sure! Thank you very much again.

**Comment by DOFfactory** [comment]
Ok, maybe one little "bug" I can see as I work now with the document. Any reference that is at the beginning of the line in VScode does not highlight with the colour defined.

**Comment by notZaki** [comment]
Yea, lines that begin with '@' will not highlight because I couldn't come up with a simple regex that could recognize references at the beginning of a line while not breaking everything else at the same time.

I don't typically start lines with a reference anyways, so I didn't see it as a problem.
But if that's something that comes up often, then I can add a regex specifically for references at the beginning of a line.

**Comment by notZaki** [comment]
The strange highlights are a concern. 
If possible, could you include an example of when the highlights misbehave?

The latex citations are somewhat easier because of their specific markup, whereas pandoc's simpler markup means having to worry about other use-cases where `@text` might be used, like email addresses. 
If it wasn't for that, it would be a simple match: highlight any word after an `@`.

I managed to highlight references at the beginning of a new line by using a negative lookbehind, but I'm not a fan of those and opted not to use it. I expected them to also work with a positive lookbehind for a linebreak, but couldn't get that to work.   

The packaged was updated with a newer regex, which might fix the strange highlights or maybe not--hopefully it doesn't breaking anything new at least.

**Comment by DOFfactory** [comment]
I just checked-out the update, and it seems all good now. 

Regarding the beginning of the new line, I am afraid, it will not be possible to avoid the negative look-behind. But it made me think, as this occurs only at the beginning of paragraphs, there should be (given the fact that this is pandoc markdown) always an empty line before. Therefore something along the line `\n + @text` should be relatively easy to put into regexp.

**Comment by notZaki** [comment]
The [existing regex](https://github.com/notZaki/PandocCiter/blob/b67a13e8e9197f5a777c39b5bb5b5dabed591347/syntaxes/citations.json) tried to look for a preceeding newline, and [it should've worked](http://regexstorm.net/tester?p=%28%3f%3c%3d%5b%5cs%5cr%5cn%5c%5b%5d%29%40+%28.*%3f%29+%28%3f%3d%5b%5cs%5cr%5cn%5c%5d%5d%29&i=%40shouldntHighlight+but+%40thisDoes+and%0d%0a%40thisToo+&o=x),  but vscode disagrees. 

I've updated the package with a newer regex which should--fingers crossed--recognize references that start on a new line.

**Comment by DOFfactory** [comment]
Hi @notZaki, many thanks for your work, I can confirm that the update of regex works. I am not sure whether you want to further tweak it, as it works sufficiently now. According to the pandoc documentation, if you list multiple citations, they should be separated by a semicolon. This is highlighted together with the reference, which is correct. However, if you follow the reference with a simple comma, it is highlighted as well. It does not bother me much, as your syntax does the job, I just report if you further want to perfect it :)

In any way, thank you for your job in addressing my query so quickly, I am very very happy with the result.

**Comment by notZaki** [comment]
Commas and other disallowed delimiters should be ignored in the updated release. 
I'm afraid a period will still get highlighted because I wasn't sure if `@ref.key` is valid or not.

I might assign an existing scope to the citations in the future. That way, highlighting will be enabeled without needing an `editor.tokenColorCustomizations` config.

Thanks for debugging the intermediate versions. I tend to use the `[@reference]` syntax so I would've been oblivious to any of these problems.
And thanks also for making the suggestion in the first place. I've struggled to locate references in the past and resorted to `Ctrl + F -> @*`, and it never occurred to me that they could be highlighted.

**Comment by notZaki** [comment]
The citation scope was changed in the latest release to `string.other.link.description.markdown.citation`. 
It now piggy-backs on an existing scope, so citations should highlight automatically with most themes.

The theme's colour can still be overwritten in vscode's settings JSON using the snippet in an earlier reply, just replace the line `"scope": "pandoc.citation",` with `"scope": "string.other.link.description.markdown.citation",`.

**Comment by DOFfactory** [comment]
Hi @notZaki, thanks for the update. Unfortunately, all the citations in brackets that are followed by a full stop (`...[@xxx].`) or comma (`...[@yyy],...`) do not follow the color coding and remain default coloured.

**Comment by notZaki** [comment]
That's interesting. They still work when there is no period or comma?
All `[@xxx]` references stopped working for me in the recent vscode version 1.28.0. Or rather, they still highlight, but under a different scope.

Anyways, the latest version 0.1.1 of the package should hopefully fix it.

**Comment by DOFfactory** [comment]
Ok, a little bit better. Now all the references are color coded, however, I have a paragraph with `...[@reference1; @reference2; @reference3] with an additional @reference4 and the rest of the sentence ... to a full stop` where all of this is highlighted.

I think before it was better, when the search did not highlighted the brackets. This might avoid cases when a part of the sentence is separated by a semi-colon, and before it there is a bracketed refence.

**Comment by DOFfactory** [comment]
Thanks for finding the culprit. Interestingly, not all brackets are coloured. In the case of `[@reference]` everything is coloured, however, if I have anything else in the brackets, e.g. `[taken from @reference]` or `[@reference, p. 51]` the brackets are not coloured. Hope this helps. I am fine with the result at the moment, better than nothing. Thanks for the great work!

**Comment by notZaki** [comment]
That somewhat makes sense. 
I had to split it into two scopes: a greedy one that highlights anything starting from `[@`  to `]`, and a more conservative one that starts when there is a space followed by `@`.

It broke earlier because both scopes were being activated.

Although, I would expect `[@reference, p. 51]` to highlight everything.

**Comment by DOFfactory** [comment]
Yes, sorry, you are correct, I had to delete that part incorrectly reported. 

Your description makes me wonder, whether the two scenarios would be able to merge into one, i.e. look either for space+@ or [+@ and highlight everything until comma, ;, ], ?, !, and full-stop+space. This should leave email addresses intact. Moreover, I cannot think of any other character that shoud be included after such reference(s). Am I right, or I am still missing something from the proposed syntax?

**Comment by notZaki** [comment]
Yea, the old implementation was along those lines: it looked for either a new line, space, or `[` before an `@`.

But the recent version of vscode has its own scope and highlighting for `[xxx]`. The nice thing is that `[@xxx]` gets automatically highlighted without needing this extension at all, but that's more of a bug than a feature (only one bracket gets highlighted). 
I had to make a separate, more aggressive, scope for `[@xxx]` to wrestle against vscode's default.

**Comment by notZaki** [comment]
The latest release (0.1.3) should highlight things the way they used to be. 
Only the `@xxx` part will be highlighted, regardless of whether it is inside or outside square brackets.

**Comment by DOFfactory** [comment]
Excellent, can confirm works perfectly! Great job and thanks!
