### ISSUE TITLE
suggestion in (@)

### ISSUE THREAD

**Issue by tkkuma-k** [notZaki/PandocCiter#16]
In my Mac OS environment, autocomplement suggestion is shown in cases: ( @), [ @], [@] but not (@).
I want your product to suggest it in (@) case.
In our field citation is always in (), so I would not like to add extra space " ".

**Comment by notZaki** [comment]
Although it is possible to add this feature, I think it might be better to use the `[@key]` syntax and then specify a csl file which will format the citation in the output. 
The advantage of using a csl file is that the format can easily be changed later (in case submitting to a different journal) and the bibliography will also be formatted appropriately. 
Examples of using a csl file are in the [pandoc manual (demo 24)](https://pandoc.org/demos.html) and [csl files are available here](https://github.com/citation-style-language/styles).

If you still prefer to use `(@key)` syntax instead of using a csl, then I can try looking into adding this feature.

**Comment by tkkuma-k** [comment]
Thank you for your suggestion!!
[@key] works well in my environment!
I will use [@key] and csl formatting.

**Comment by notZaki** [comment]
I'm glad it worked out. Cheers!
