### ISSUE TITLE
How to show multiple citekeys simultaneously? 

### ISSUE THREAD

**Issue by TomBener** [notZaki/PandocCiter#17]
Thanks for the amazing project!

I remembered that when I first used Pandoc Citer, multiple citekeys could show up at the same time which was the same as the demo figure in `README.md`, so I could pick one that I want in a breeze. However, I have no idea why only one citekey shows up currently, even though I can switch them use keyboard `↓` and `↑`.

![CleanShot 2020-12-10 at 14 48 39](https://user-images.githubusercontent.com/49151155/101732292-ef3cbb80-3af7-11eb-8b63-66e009a8e49d.gif)

I'd like to show multiple citekeys simultaneously as previous. And the settings are as follows. Could you help with the small issue? Thanks so much!

<img width="1440" alt="截屏2020-12-10 14 59 51" src="https://user-images.githubusercontent.com/49151155/101732572-62dec880-3af8-11eb-8be5-005c6523e26f.png">

**Comment by notZaki** [comment]
Whoa, that looks strange indeed.

I don't think there's been any major changes to the package that could cause this behavior, but I'll double check if I can reproduce this on any of my systems.

Since you said that the suggestions can still be accessed with the arrow keys, maybe it's a window sizing issue. Try opening the command palette, e.g. `Ctrl Shift P`, and then search for `Reset Suggest Widget Size`.

**Comment by TomBener** [comment]
@notZaki Try to `Reset Suggest Widget Size`, and it works instantly. Really thank you 🥰️

**Comment by notZaki** [comment]
Glad it worked out!
