### ISSUE TITLE
Can you make "PandocCiter.DefaultBib" option be a list of '.bib' instead of one ?

### ISSUE THREAD

**Issue by akharrou** [notZaki/PandocCiter#18]
Would be really useful to be able to specify more than one '.bib' file for autocompletion.
Thanks for the great extension, it's really nice.

**Comment by akharrou** [comment]
Didn't see this: "Multiple bib files can be included if separated by comma, e.g. `[path/to/refsA.bib, path/to/refsB.bib]`"

**Comment by notZaki** [comment]
Sorry, this slipped under my radar.

This is a good suggestion, and I wish I had made `DefaultBib` accept multiple files from the beginning. It'll take some time for me to figure out how to make this change without disrupting existing users.

In the meantime, one workaround is to defined a markdown file with the bib files, so the content of this file would look like:
```
---
bibliography: [path/to/A.bib, path/to/B.bib, path/to/C.bib
---
```
and then set `"PandocCiter.RootFile": "path/to/above/file.md"`.

**Comment by CLRafaelR** [comment]
@notZaki 

I did [your approach](C:/Users/a6m1-/Dropbox/Masataka/linguistics/doc-creation/bibs/English.bib): I created a md file in which I specified the path to my bib files, and set `PandocCiter.RootFile`. However, this throws `Duplicate Key(s)` message and prevents PandocCiter from auto-completing citation keys, even though the bib files have mutually different keys and bibliographic information. The message disappears when I specify only one path to a bib file. That is, I can specify only one bib file.

How should I fix that? Do you have any idea?

**Comment by notZaki** [comment]
@CLRafaelR 
The relevant code for parsing the default bib file is: https://github.com/notZaki/PandocCiter/blob/3f479aee7c3fa1e2409d41fca2ee9bbb58befb0d/src/components/manager.ts#L78-L84

It would have to be updated to look something like (this is how the rootfile is parsed so the code will have to be modified a bit):
https://github.com/notZaki/PandocCiter/blob/3f479aee7c3fa1e2409d41fca2ee9bbb58befb0d/src/components/manager.ts#L68-L75

I am surprised by the `Duplicate Key(s)` message because that shouldn't depend on how the bib files are included. From what I recall, the message should list which keys are duplicates. Have you already checked that the keys in the message are not repeated in the bib files?
In any case, the message could be disabled by commenting out:
https://github.com/notZaki/PandocCiter/blob/3f479aee7c3fa1e2409d41fca2ee9bbb58befb0d/src/providers/completer/citation.ts#L151

**Comment by CLRafaelR** [comment]
I've already checked that my bib files had no duplicate. Now the warning message disappeared somehow, but the message seemed to say every single key has a duplicate when the message appeared.

**Comment by notZaki** [comment]
This is a bit late, but the latest release (`0.10.0`) has a new configuration option `PandocCiter.DefaultBibs` (with an "s"!) which will accept an array of files.
