### ISSUE TITLE
Feature Request: support for .pmd extension

### ISSUE THREAD

**Issue by DavidSorge** [notZaki/PandocCiter#19]
This is great; is it possible to set it up so that the program recognizes `.pmd` files as markdown?
`.pmd` files are a python analog to R-markdown `.rmd` files, used with [pweave](https://mpastell.com/pweave/) (a python analog to knitr).

Being able to use PandocCiter would enable a really nice `.pmd`-based workflow for creating academic articles.

**Comment by notZaki** [comment]
That sounds doable.

Are you using any other extension that has pweave support?

**Comment by DavidSorge** [comment]
At the moment, just [this one](https://marketplace.visualstudio.com/items?itemName=jameselderfield.language-weave)

I did find an alternate pathway to solving the citation issue through the [Citation Picker for Zotero](https://marketplace.visualstudio.com/items?itemName=mblode.zotero), which meshes with a Zotero extension.

**Comment by notZaki** [comment]
Yup, the zotero extension is convenient too. It can be less picky about languages because the onus is on the user to activate it with the keyboard shortcut.

I asked about other extensions because if you weren't using anything else, then `Ctrl Shift P -> Change Language Mode -> Markdown` could've worked.
I'll try to get this extension to recognize the pmd language defined by `language-weave`.

**Comment by notZaki** [comment]
I tried adding pweave support in the latest version `0.8.0`. Hopefully it works.

**Comment by DavidSorge** [comment]
Thanks so much! I'll check it out!

**Comment by DavidSorge** [comment]
... And it works like a charm! I've never seen a feature request handled this quickly! Much obliged!
