### ISSUE TITLE
Go to definition on click and pop-up with citation information on hover

### ISSUE THREAD

**Issue by mihaiconstantin** [notZaki/PandocCiter#28]
Thanks for this awesome and lightweight extension! I think it would be really handy to have support for:

1. a pop-up that shows the title, year, and author of a `BibTeX` citation on hover

2. jumping to where the citation is defined in the `.bib` file on `cmd/control + click` (i.e., similar to what the `Markdown Notes` extension does [here](https://github.com/kortina/vscode-markdown-notes/blob/master/src/BibTeXCitations.ts)).

What do you think?

**Comment by notZaki** [comment]
Those are good suggestions @mihaiconstantin !

Having the information on-hover is something I would find useful too. I sometime retype a citation when I have doubts in order to confirm the title/year/author in the suggestions window, but that's not elegant.
I haven't played with vscode's hovering capabilities, so not sure how difficult this will be to implement, but maybe I'll look into this if I have time, unless someone else beats me to it.

Jumping to the bibtex entry in the `.bib` file could also be useful, but if the `Markdown Notes` extension already does this, then can't it be installed/used to get this feature, or am I missing something?

**Comment by Dominic-DallOsto** [comment]
I think I've addressed this in #29. Let me know what you think!

**Comment by mihaiconstantin** [comment]
@notZaki, my apologies for the slow response--I was caught up with teaching these days. About your comment below, my understanding is that *Markdown Notes* is no longer maintained and some of its features are now part of [*Foam*](https://github.com/foambubble/foam). Personally, I think it is handy to have the functionality I suggested part of *PandocCiter*. It then has all you need to quickly draft documents.

> Jumping to the bibtex entry in the `.bib` file could also be useful, but if the `Markdown Notes` extension already does this, then can't it be installed/used to get this feature, or am I missing something?

@Dominic-DallOsto, thanks for this! I will comment on the #29 thread.

**Comment by mihaiconstantin** [comment]
This can be closed based on #29. Thanks, @Dominic-DallOsto!
