### ISSUE TITLE
Add support for -@citekey to suppress author name

### ISSUE THREAD

**Issue by sbaack** [notZaki/PandocCiter#3]
First, thank you so much for this extension!

Pandoc provides the -@citekey syntax to suppress the name of the author(s) and only show the publication year in the converted document. This is very useful when the name of the author is already mentioned in the text. For example, "As Habermas mentioned earlier...[-@Habermas1991]" will turn into "As Habermas mentioned earlier...(1991)".

Currently, PandocCiter won't trigger if the @ is right after some text without a space to avoid problems with email addresses. Unfortunately, this means that no suggestions are triggered when I want to use Pandoc's syntax for suppressing author names. It would be great if you could:

1. Add an exception to the rule so that suggestions are triggered when typing -@
2. Expand the solution for #1 and add syntax highlighting for Pandoc citations with suppressed author names

**Comment by notZaki** [comment]
Thanks for the suggestion. I use numerical citations, e.g. "As mentioned earlier ... [1].", so I forgot that `-@key` existed.

The updated version of the package (0.1.5) should trigger with `-@` and should highlight `[-@key]` as well. 
It's a lazy implementation, so even `----@` or `asdf-@` will trigger the citations. Might restrict it in the future. Or might not. I'm not the syntax police. 

Since this is unfamiliar territory, is `-@key` always used inside square brackets or does it also have uses without brackets?

**Comment by sbaack** [comment]
Wow, thanks for the quick update!

I think it's more or less conventional to write `-@key` inside square brackets, but it doesn't have to be. You can also write "As Habermas -@Habermas1991 mentions" and Pandoc will convert it to "As Habermas (1991) mentions".

Importantly though, you sometimes want to refer to several sources from the same author using `-@key`, as in

> As Habermas [-@Habermas1984; -@Habermas1991] explained earlier...

Pandoc will turn this into "Habermas (1984, 1991)". Your current implementation works, but it doesn't highlight the minus sign if it is not directly after a square bracket. In the example above, the second `-` from `-@Habermas1991` is not highlighted. Not really an urgent problem though, thanks again! :-)

**Comment by notZaki** [comment]
Thanks for the info. Latest update (0.2.0) should fix the highlights.

Missing highlights on a minus is just too annoying to ignore. 😁

**Comment by sbaack** [comment]
Haha thanks a lot, it works perfectly now :-)
