### ISSUE TITLE
Autocompletion on BibTeX files not functioning after recent update

### ISSUE THREAD

**Issue by hxtmike** [notZaki/PandocCiter#41]
The autocompletion of citations on BibTeX files is not working after updating to the latest version (v 0.10.0).

While other autocompletion, such as those on crossref on figures or tables, still works well.

I tried rolling back to version 0.9.3, and it works fine again.

OS: WSL2 on Windows 10
VSCode:1.78.2

**Comment by notZaki** [comment]
Thanks for opening the issue. That's an odd combination. Usually nothing works or it all works. 

There was a change in how the bib files were loaded with version 0.10.0, so that's likely to blame. I tried to make it behave a bit more like the old way, so could you try version 0.10.1 (just released now) and see if it helps?

**Comment by Raychanan** [comment]
I had the same issue. I tried using both V0.10.1 and V0.10.0, but neither of them worked for autocomplete. However, when I downgraded to version 0.9.3 which was released a year ago, the functionality started working again.

**Comment by notZaki** [comment]
There's another attempt to try and fix this with version 0.10.2. 

There is also this [sample repository](https://github.com/notZaki/PandocCiterSample), and you can check if the extension works on that. It works on my end both locally and on codespaces, but there's surely something wrong because it's not working for everyone. 
The only time I've noticed the suggestions not showing up is if vscode has a new update or the extension is freshly installed. In those cases, reloading vscode (or closing/re-opening it) tends to fix things.

**Comment by Raychanan** [comment]
I understand what you're saying. I had the same issue with my vscode after upgrading to 0.10.1 and even killing it didn't solve the problem. However, your 0.10.2 version fixed everything perfectly! Thank you for developing this extension that saved me so much time and for fixing the issue promptly!

**Comment by hxtmike** [comment]
It works perfectly as I upgrade it to v0.10.2. 
Thanks so much for this swift repair!
