### ISSUE TITLE
Sublime Text

### ISSUE THREAD

**Issue by NatalieGates** [notZaki/PandocCiter#7]
I've used sublime text for many years so it is difficult to change to a different editor. Your extension works so amazingly well on VSC. I would love if we had something similar for ST. I currently use [citer](https://github.com/mangecoeur/Citer) which is seriously outdated but gets the job done. However, it is not as intuitive as PandocCiter. I am sure this is a major undertaking, but if it's possible, I and many others would appreciate it.

**Comment by notZaki** [comment]
Thanks for the positive comments!

I'm not familiar with SublimeText's development process for extensions since it uses a different language than VSC.
Your best bet would be someone updating the citer extension with the desired features, or getting a related extension, such as [LaTeXTools](https://github.com/SublimeText/LaTeXTools), to support markdown. 

I used to use ST in the past, and my way of getting bibtex completion was to change the file syntax to LaTeX and then relying on LaTeXTools. Unfortunately, this requires inserting citations via `\cite{key}` instead of `@key`, so the references would only show up properly on pdf output.

**Comment by NatalieGates** [comment]
Thanks!

I like your suggestions of using LaTeXTools. I think that will work nicely.

Before creating this issue I had thought about reaching out to the extension authors on ST but I noticed it had not been updated for 5 years. It seems abandoned :(

Thanks so much for responding! Love your extension!
