### ISSUE TITLE
restructuredtext implementation?

### ISSUE THREAD

**Issue by Nadano** [notZaki/PandocCiter#9]
After struggling with markdown for complex documents I decided to try restructuredtext (with sphinx) and I'm liking it a lot. Sadly, no citation helper exist for this language yet.

I was wondering how difficult it would be to make your extension work with it. If in not wrong the differences in implementation with markdown are quite small: instead of @, rst require :cite: and rather than having the bibtex file declared in the yaml header, rst declares it at the bibliography insertion point .. bibliography:: refs.bib

More information please refer to:
https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html

Do you believe it would be possible to implement it easily?

**Comment by notZaki** [comment]
I gave it a quick shot by modifying a few lines (commit: 4ce4aa4e274731271fb2eaec185fdbbe4e79011e) and, although not perfect, it did seem to work.

You can try it out by cloning the [sphinx branch](https://github.com/notZaki/PandocCiter/tree/sphinx) and then building it locally.
Alternatively, this zip file [pandocciter-0.4.2.zip](https://github.com/notZaki/PandocCiter/files/3869963/pandocciter-0.4.2.zip) contains the `vsix` file. Someone else has already written a nice guide on [how to install from vsix](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Prereleases-(vsix)).

**Comment by Nadano** [comment]
What is not perfect? works great on my machine! the only thing I can think of is to add the ` after the reference, but apart from that it works flawlessly

**Comment by notZaki** [comment]
The issues I noticed were:

- The ` after the reference triggers the citation suggestions which have to be shooed away by hitting escape
- I'm not familiar with sphinx, but I'm assuming that multiple citations are inserted by ``:cite:`ref1, ref1` `` so it would be nice if another set of suggestions were shown after the comma.
- Based on some [quick reading](https://sphinxcontrib-bibtex.readthedocs.io/en/0.2.6/usage.html) it seems that multiple bib files are inserted on separate lines. Currently, the extension only looks for the first bibliography insertion point.

Anyways, I'm glad you found it useful. 
However, since I don't use restructured text, I probably won't support it in any official version of PandocCiter. But anyone is free to use this as a starting point and develop it further.

If you want to keep using the above version then I would suggest changing the name/details in `package.json` and rebuilding it (or I can share a new vsix with a different name), because otherwise it might get over-written by a future version of PandocCiter.

**Comment by notZaki** [comment]
Looks like this was completed (?) based on the referenced issue above, so closing this. Hope it worked out!
